# Generated by Django 5.2 on 2025-04-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customeruser_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeruser",
            name="username",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
