# Generated by Django 5.2 on 2025-04-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customeruser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeruser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
