# Generated by Django 5.2 on 2025-04-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customeruser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeruser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
